### ISSUE TITLE
[Bug] Variables.scss missing

### ISSUE THREAD

**Issue by undefinedfunction** [creativetimofficial/ct-soft-ui-design-system-pro#11]
### Version
1.0.3
### Reproduction link
http://n/a
### Operating System
OSX
### Device
Mac
### Browser & Version
N/A
### Steps to reproduce
1) Download package
2) Run npm I
3) run node ./node_modules/gulp/bin/gulp.js watch
4) Modify any scss file

You'll get the error below. 

[22:21:03] Starting 'watch'...
[22:21:12] Starting 'compile-scss'...
Error in plugin "sass"
Message:
    assets/scss/soft-design-system-pro/_variables-extend.scss
Error: File to import not found or unreadable: ../variables.
        on line 6 of assets/scss/soft-design-system-pro/_variables-extend.scss
        from line 21 of assets/scss/soft-design-system-pro.scss
>> @import "../variables";
### What is expected?
Variables.scss should exist
### What is actually happening?
It doesn't exist. 

---

**Comment by groovemen** [comment]
Hello @undefinedfunction,

Thank you for using our products and for letting us know about this issue. Until the next product update we'll ask you to fix it like this:
- please go to this file: **assets/scss/soft-design-system-pro/_variables-extend.scss** and replace the line 6 from this `@import "../variables";` into this: `@import "./variables";`

Please let us know if we can help with any other details.

Best,
Creative Tim Staff

P.S. Remember to wash your hands before coding!

**Comment by undefinedfunction** [comment]
@groovemen great stuff, that worked. Thanks you 👍
