### ISSUE TITLE
Add Image Styles to the Docs

### ISSUE THREAD

**Issue by PeterBinc** [creativetimofficial/ct-soft-ui-design-system-pro#12]
So many styles applied to images that I have no clue as to waht they do.

**Comment by groovemen** [comment]
Hello @PeterBinc,

Thank you for using our products, we'll ask you to give us more details about your issue. Or what we can help you to understand what's happening. 
Please let us know if we can help with any other details.

Best,
Creative Tim Staff

P.S. Remember to wash your hands before coding!

**Comment by PeterBinc** [comment]
No issues per se, I just wanted better Documentation for all of the image classes. There’s nothing in the Doc about what classes render what effects.

Peter Bockenthien
720-999-4169

**Comment by groovemen** [comment]
Hello again, 

Thank you for your constructive feedback, I will discuss it with my colleagues and we will integrate into a future product update a better and well-documented page for the utility classes (for images and other elements if necessary). 
Meanwhile, you can check this Bootstrap's page: https://getbootstrap.com/docs/5.0/content/images/ you will find some info about few classes that you can use for the images. 
Hope this infos helps you. 

All the best, 
Stefan
