### ISSUE TITLE
[Bug] Blurry text in main menu

### ISSUE THREAD

**Issue by rr222cy** [creativetimofficial/ct-soft-ui-design-system-pro#14]
### Version
1.0.8
### Reproduction link
https://imgur.com/JyacuU6
### Operating System
Windows 10
### Device
PC
### Browser & Version
Vivaldi 4.0
### Steps to reproduce
1. Go to: https://www.creative-tim.com/product/soft-ui-design-system-pro for example
2. Hover over main menu
3. Text is blurry ( see: https://imgur.com/JyacuU6 )

I've tested this in the latest version of Vivaldi, Edge and Firefox- all with the same blurriness. Tested on a PC running the latest version of Windows 10 with a 1080p screen.
### What is expected?
The font to be less blurry and more crisp like the other texts on the webpage.
### What is actually happening?
The text in the main menu is blurry

---

**Comment by rarestoma** [comment]
Hi @rr222cy,

Thank you for working with our products and for pointing us this issue.

We will do some tests and we will add it to the 'to do' list for the next updates.

Best regards,
Rares
