### ISSUE TITLE
[Bug] SassError: Top-level selectors may not contain the parent selector "&". 

### ISSUE THREAD

**Issue by crisstelista** [creativetimofficial/ct-soft-ui-design-system-pro#18]
### Version
Version 1.0.8
### Reproduction link
https://jsfiddle.net/
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Chrome 
### Steps to reproduce
I'm running into some issues with the Sass files. I am using Laravel 8 and I integrated this template into my resources folder. I added on my package.json all the dev dependencies existing in the json file of the template. I run the commands npm install and then npm run dev.
### What is expected?
To be able to run the commands
### What is actually happening?
ERROR in ./resources/assets/scss/presentation/soft-design-system-pro.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Top-level selectors may not contain the parent selector "&".
![image](https://user-images.githubusercontent.com/32781717/129971226-bf4c0179-e389-4e9b-9bfe-0285c29d103b.png)

![image](https://user-images.githubusercontent.com/32781717/129971250-6883e7e0-52d8-442e-9e6b-82ab3936f89d.png)

---

**Comment by rarestoma** [comment]
Hi @crisstelista,

Thank you for working with our products.

Please try replace the following line:

```
@each $prop, $value in $theme-colors {
  &.bg-gradient-faded-#{$prop}-vertical{
    background-image: radial-gradient(200px circle at 50% 70%, rgba($value, .3) 0, $value 100%);
  }
}
```

with 

```
@each $prop, $value in $theme-colors {
  .bg-gradient-faded-#{$prop}-vertical{
    background-image: radial-gradient(200px circle at 50% 70%, rgba($value, .3) 0, $value 100%);
  }
}
```

Now the error should no longer exist.

Please let me know if it works.

Best regards,
Rares

**Comment by crisstelista** [comment]
This fix the problem.

Thanks!
