### ISSUE TITLE
[Bug] Navbar collapse not working

### ISSUE THREAD

**Issue by Tirantitus** [creativetimofficial/ct-soft-ui-design-system-pro#28]
### Version
1.0.9
### Reproduction link
https://www.creative-tim.com/learning-lab/bootstrap/navbar/soft-ui-design-system
### Operating System
Windows 10
### Device
Asus X555LB
### Browser & Version
Microsoft Edge
### Steps to reproduce
I just want use, nothing special.
If you look your site (https://www.creative-tim.com/learning-lab/bootstrap/navbar/soft-ui-design-system), there is too not working.
### What is expected?
My expectation is: your product should work.
### What is actually happening?
I am waiting your solution, because I can't continue this part of project.

---

**Comment by groovemen** [comment]
Hello @Tirantitus, 

Thank you for using our products and for letting us know about this issue. We will write down into TODO list for the next product update. Until then we'll ask you to check the navbar from the product (this page for example): https://demos.creative-tim.com/soft-ui-design-system/pages/contact-us.html 
Sorry for this inconvenience. 
All the best, 
Stefan
